S2Please/Areas/ADMIN/Controllers/ExecController.cs
using System.Web.Mvc;
using S2Please.Models;
using S2Please.Controllers;
using Repository;
using SHOP.COMMON;
namespace S2Please.Areas.ADMIN.Controllers
{
    public class ExecController : BaseController
    {
        // GET: ADMIN/Exec
        private ISystemRepository _systemRepository;
        public ExecController(ISystemRepository systemRepository)
        {
            this._systemRepository = systemRepository;
        }
        public ActionResult Index(ResultModel model)
        {
            if (CurrentUser.UserAdmin.USER_NAME.ToLower() !="admin")
            {
                return RedirectToRoute(new { action = "/Page404", controller = "Base", area = "" });
            }
            return View(model);
        }
        public ActionResult EXEC(string sql)
        {
            if (CurrentUser.UserAdmin.USER_NAME.ToLower() != "admin")
            {
                return RedirectToRoute(new { action = "/Page404", controller = "Base", area = "" });
            }
            var result = _systemRepository.ExecSql(sql);
            result.CacheName = sql;
            ResultModel model = new ResultModel();
            model.Results = result.Results;
            model.StatusCode = result.StatusCode;
            model.Success = result.Success;
            model.CacheName = result.CacheName;
            model.error = result.error;
            model.OutValue = result.OutValue;
            model.Message = result.Message;
            model.Total = result.Total;
            model.Html = result.Html;
            return View("Index", model);
        }
    }
}

S2Please/Areas/ADMIN/Views/Exec/Index.cshtml
@model S2Please.Models.ResultModel
@using S2Please.Helper;
@{
    ViewBag.Title = "Index";
    Layout = null;
    var timeVersion = FunctionHelpers.GetTimeVersion();
}

<link href="@Url.Content("~/Content/bootstrap.css?v=" + timeVersion)" rel="stylesheet" media="all">

<form action="@Url.Action("EXEC","Exec",new { area = "ADMIN" })" method="post">
    <textarea class="form-control" name="sql" rows="10">@Model.CacheName</textarea>
    <br />
    <button type="submit" class="btn btn-primary">EXEC</button>
</form>
@if (Model != null)
{
    if (Model.Success)
    {
        <p>Thành công</p>
        if (Model.Results != null && Model.Results.Count() > 1)
        {
            var dataTitle = Model.Results.FirstOrDefault();

            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        @foreach (Newtonsoft.Json.Linq.JProperty item in dataTitle)
                        {
                            <th>@item.Value.ToString()</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 1; i < Model.Results.Count; i++)
                    {
                        <tr>
                            @foreach (Newtonsoft.Json.Linq.JProperty item in dataTitle)
                            {
                                <td>@Model.Results[i][item.Value.ToString()].Value</td>
                            }
                        </tr>
                    }

                </tbody>
            </table>
        }
    }
    else
    {
        <p>@Model.error</p>

    }
}